# Generated by Django 4.1.2 on 2022-10-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='moods',
            field=models.ManyToManyField(to='main_app.mood'),
        ),
    ]
